using System.Windows.Forms;
using Eplan.EplApi.Scripting;

public class FormTemplate : Form
{
  public FormTemplate()
  {
    InitializeComponent();
  }

  #region Code generated by the Windows Form Designer
  private System.ComponentModel.IContainer components = null;

  protected override void Dispose(bool disposing)
  {
    if (disposing && (components != null))
    {
      components.Dispose();
    }
    base.Dispose(disposing);
  }

  private void InitializeComponent()
  {
      this.SuspendLayout();
      // 
      // FormTemplate
      // 
      this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
      this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
      this.ClientSize = new System.Drawing.Size(284, 261);
      this.Name = "FormTemplate";
      this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
      this.Text = "Template";
      this.ResumeLayout(false);

  }
  #endregion

  [Start]
  public void Function()
  {
    FormTemplate form = new FormTemplate();
    form.ShowDialog();
  }
}